BavoZone-V.1.0-main/BravoZone/BravoZone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('main.urls')),
    path('account/' , include('account.urls')),
    path('evaluation/' , include('evaluation.urls')),
    
] +static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

BavoZone-V.1.0-main/BravoZone/account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("admin/view/", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/<int:user_id>", views.profile, name="user_profile"),
    path("all/employee/", views.all_emploee, name="all_emploee"),
    path("signup/employee", views.register_employee, name="register_employee"),
    path("profile/<int:user_id>/edit", views.edit_profile, name="edit_profile")
]

BavoZone-V.1.0-main/BravoZone/evaluation/urls.py
from django.urls import path
from evaluation import views


app_name = "evaluation"

urlpatterns = [
    path("tasks/", views.task_list, name="task_list"),
    path("tasks/create/", views.task_create, name="task_create"),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),
    path('task/<int:task_id>/update_status/', views.update_task_status, name='update_task_status'),
    path('task/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('mytask', views.my_tasks, name='my_task_list')
]

BavoZone-V.1.0-main/BravoZone/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('leaderboard/', views.leader_bord, name='leader_bord'),

]

BavoZone-V.1.0-main/BravoZone/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from account.models import User
from django.conf import settings

BavoZone-V.1.0-main/BravoZone/main/forms.py
from django import forms
from .models import PreviousProject
from .models import Comment

class PreviousProjectForm(forms.ModelForm):
    class Meta:
        model = PreviousProject
        fields = ['title', 'content', 'image', 'link', 'date']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

BavoZone-V.1.0-main/BravoZone/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse


import sys

sys.path.append(".")
from evaluation.models import Task
from account.models import User


def home_view(request: HttpRequest):
    return render(request, "main/home_view.html")


def leader_bord(request):
    employees = User.objects.filter(is_superuser=False, is_staff=False)

    leaderboard_list = []
    for employee in employees:
        employee_tasks = Task.objects.filter(assigned_to=employee)
        print(employee_tasks)
        completed_tasks_points = []
        for task in employee_tasks:
            if task.status == "completed":
                completed_tasks_points.append(int(task.points))

        print(completed_tasks_points)

        leaderboard_list.append(
            {
                "employee": employee,
                "number_of_tasks": len(employee_tasks),
                "total_points": sum(completed_tasks_points),
            }
        )
        print(leaderboard_list)

    ordered_list = sorted(
        leaderboard_list, key=lambda x: x["total_points"], reverse=True
    )

    

    return render(
        request,
        "main/leader_bord.html",
        {"first_three_employees": ordered_list[0:3], "ordered_list": ordered_list},
    )

BavoZone-V.1.0-main/BravoZone/main/templates/main/base.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
  <title>{% block title %} {% endblock %}</title>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{%static 'img/favicon.png'%}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,400,500,700"
    rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">
      <!-- profil-->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static  'vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css'%}" rel="stylesheet">

</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between">

      <div class="logo">
        <!-- Uncomment below if you prefer to use an text logo -->
        <!-- <h1><a href="index.html">NewBiz</a></h1> -->
        {% if request.user.is_superuser %}

        <a href="{% url 'account:home' %}"><img src="{% static 'img/bzlogo.png'%}" alt="" class="img-fluid" width="70px" height="outo"></a>
        {%else%}
        <a href="{% url 'main:home_view' %}"><img src="{% static 'img/bzlogo.png'%}" alt="" class="img-fluid" width="70px" height="outo"></a>

        {%endif%}
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          {% if request.user.is_superuser %}
          <li><a class="nav-link scrollto " href="{%url 'account:home'%}">Home</a></li>
          {%else%}
          <li><a class="nav-link scrollto " href="{%url 'main:home_view'%}">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          {%endif%}
          {% if request.user.is_authenticated and not request.user.is_superuser %}
          <li><a class="nav-link scrollto" href="{%url 'account:profile'%}">Profile</a></li>
          <li><a class="nav-link scrollto " href="{%url 'main:leader_bord'%}">leaderboard</a></li>
          <li><a class="nav-link scrollto " href="{% url 'evaluation:my_task_list' %}">My task</a></li>
          <li><a class="nav-link scrollto " href="{% url 'account:all_emploee' %}">All employees</a></li>
          <li><a class="nav-link scrollto" href="#">{{ user.first_name }}</a></li>

          {%endif%}
          {% if request.user.is_superuser %}
          <li><a class="nav-link scrollto " href="{%url 'main:leader_bord'%}">leaderboard</a></li>
          <li><a class="nav-link scrollto " href="{% url 'evaluation:task_list' %}">All tasks</a></li>
          <li><a class="nav-link scrollto " href="{% url 'account:all_emploee' %}">All employees</a></li>
          <li><a class="nav-link scrollto" href="#">{{ user.username }}</a></li>

          {%endif%}

          </li>

          <li><a class="nav-link scrollto" href="#acconut">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                <path fill-rule="evenodd"
                  d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
              </svg>
            </a></li>
          {% if request.user.is_authenticated %}
          <li><a class="nav-link scrollto" href="{% url 'account:logout' %}">Logout</a></li>
          {%else%}
          <li><a class="nav-link scrollto" href="{% url 'account:logout' %}">Login</a></li>
          {%endif%}

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- #header -->
  {% block content %}
  {% endblock %}
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-info">
            <h3>BravoZone</h3>
            <p>
              "Welcome to Bravo zone , where recognition and motivation meet in perfect harmony! Step into a world where
              outstanding achievements are celebrated, and hard work is rewarded. We're thrilled to have you join our
              community of excellence, where every milestone becomes a stepping stone towards greater success. Together,
              let's create a culture of appreciation and inspire each other to reach new heights. Welcome!"
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Our team</h4>
            <ul>
              <li><a href="#">Basma Alshahrani</a></li>
              <li><a href="#">Ghaida allhyani</a></li>
              <li><a href="#">Nada Almutairi</a></li>
              <li><a href="#">Manal Alzahrani</a></li>
              <li><a href="#">Lama Alsharif</a></li>
              

            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              SaudiArabia, Riyadh<br>
              AlMalqa <br>
              <strong>Phone:</strong> +966 556122568<br>
              <strong>Email:</strong> Basmabadya@gmail.com<br>

            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <a href="index.html"><img src="{% static 'img/bz2logo.png'%}" alt="" class="img-fluid" width="250px"
                height="outo"></a>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>BravoZone</strong>. All Rights Reserved
      </div>

    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js'%}"></script>
  <script src="{% static 'vendor/aos/aos.js'%}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js'%}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js'%}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js'%}"></script>

</body>

</html>

BavoZone-V.1.0-main/BravoZone/main/templates/main/home_view.html
{% extends 'main/base.html' %}
{% block title %} Home  {% endblock %}
{% block content %}
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="clearfix">
    <div class="container" data-aos="fade-up">
      <div class="hero-img" data-aos="zoom-out" data-aos-delay="200">
        <img src="static/img/hero-img.svg" alt="" class="img-fluid">
      </div>
      <div class="hero-info" data-aos="zoom-in" data-aos-delay="100"> 
        <h2 class=" mt-3 mb-3 text-decoration-none display-5 text-light font-weight-bold titleh ">Unleash your potential</h2>
        <h3 class=" mt-5 mb-5 text-decoration-none display-6 text-warning ">Reap the rewards!</h3>        <div>
          {% if not request.user.is_authenticated %}
          <a href="{%url 'account:signup'%}" class="btn-get-started scrollto">Get Started</a>
          {%endif%}
        </div>
      </div>
    </div>
  </section><!-- End Hero Section -->
  <main id="main">
    <!-- ======= About Section ======= -->
    <section id="about">
      <div class="container" data-aos="fade-up">
        <header class="section-header">
          <h3>About Us</h3>
          <p> 
            At Bravo Zone, we are passionate about empowering companies to cultivate a culture of appreciation and motivation. Our platform revolutionizes how tasks are assigned, evaluated, and rewards are distributed, all with the goal of recognizing and fostering outstanding performance. Join us on this journey of inspiring excellence and creating a workplace where every achievement is celebrated and every employee thrives.
          </p>
        </header>
        <div class="row about-container">
          <div class="col-lg-6 content order-lg-1 order-2">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bi bi-person-vcard"></i></div>
              <h4 class="title"><a href="">Peer Recognition and Feedback</a></h4>
              <p class="description">Staff members can identify and appreciate each other's achievements and exchange comments across the platform.</p>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="200">
              <div class="icon"><i class="bi bi-brightness-high"></i></div>
              <h4 class="title"><a href="">Manager Recognition and Guidance</a></h4>
              <p class="description">Managers and colleagues can provide constructive guidance and recognize the distinct achievements of staff.</p>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="300">
              <div class="icon"><i class="bi bi-stars"></i></div>
              <h4 class="title"><a href="">Point-Based Rewards</a></h4>
              <p class="description">Points are allocated for each achievement or goal accomplished, and staff members with a high number of points receive rewards and recognition.</p>
            </div>

          </div>

          <div class="col-lg-6 background order-lg-2" data-aos="zoom-in">
            <img src="static/img/about-img.svg" class="img-fluid" alt="">
          </div>
        </div>

        <div class="row about-container mb-5">
          <div class="col-lg-6 background order-lg-1" data-aos="zoom-in">
            <img src="static/img/about-extra-2.svg" class="img-fluid" alt="">
          </div>

          <div class="col-lg-6 content order-lg-2 order-2 mt-5">
         
            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bi bi-card-checklist"></i></div>
              <h4 class="title"><a href="">Leaderboards</a></h4>
              <p class="description"> The platform displays leaderboards showcasing the best performers and highest achievers, promoting positive competitiveness among staff.</p>
            </div>
            <div class="icon-box" data-aos="fade-up" data-aos-delay="200">
              <div class="icon"><i class="bi bi-pencil-square"></i></div>
              <h4 class="title"><a href="">Profile Management</a></h4>
              <p class="description">Each staff member can manage their personal file, add experiences, courses, record achievements and projects. Managers can provide guidance and adjust staff information.</p>
            </div>
            <div class="icon-box" data-aos="fade-up" data-aos-delay="300">
              <div class="icon"><i class="bi bi-list-task"></i></div>
              <h4 class="title"><a href="">Task Assignment</a></h4>
              <p class="description">Managers can assign tasks to staff members, raising the level of evaluation and performance.
              </p>
            </div>

          </div>

          
        </div>

      

      </div>
    </section>
  </main>
{%endblock%}

BavoZone-V.1.0-main/BravoZone/main/templates/main/leader_bord.html
{% extends 'main/base.html' %}
{% block title %} LeaderBoard  {% endblock %}
{% block content %}

<div class="container employee">

    <div class="container">
        <div class="text-center pt-3 pb-2 d-flex justify-content-center ">
                      
            <h2 class="text-black mb-5"> <span> <i class="bi bi-list-stars"></i></span> LeaderBoard </h2>
          </div>
        <div class="row">
           {% for employee in first_three_employees %}
           {% if forloop.counter == 1 %}
            
            <div class="col-md-4">
                <div class="card user-card">
                    <div class="card-header">
                        <h6 class="mb-0 display-6 "><span class="badge bg-c-blue rounded-5 ">{{forloop.counter}}st </span></h6>
                    </div>
                    <div class="card-block">
                        <div class="user-image">
                            <img src="{{ employee.employee.profile_picture.url }}" class="img-radius " >
                        </div>
                        <h6 class="f-w-600 m-t-25 m-b-10">{% if employee.employee.first_name %}{{ employee.employee.first_name }} {{ employee.employee.last_name }}{% else %} {{ employee.employee.username }} {% endif %}</h6>
                        <hr>
                        <p class="text-muted m-t-15">Point: {{ employee.total_points }} <i style="color: #ffcc00;" class="bi bi-star-fill"></i></p>
                     
    
                        <div class="bg-c-blue counter-block m-t-10 p-30 rounded">
                          <a class="btn text-light" href="/account/profile/{{employee.employee.id}}">Read More</a>
                        </div>
                       
                       
                    </div>
                </div>
            </div>
            {% endif %}
            {% if forloop.counter == 2 %}
            <div class="col-md-4">
                <div class="card user-card">
                    <div class="card-header">
                        <h6 class="mb-0 display-6 "><span class="badge bg-c-green rounded-5 ">{{ forloop.counter }}nd </span></h6>
                    </div>
                    <div class="card-block">
                        <div class="user-image">
                            <img src="{{ employee.employee.profile_picture.url }}" class="img-radius" alt="User-Profile-Image">
                        </div>
                        <h6 class="f-w-600 m-t-25 m-b-10">{% if employee.employee.first_name %}{{ employee.employee.first_name }} {{ employee.employee.last_name }}{% else %} {{ employee.employee.username }} {% endif %}</h6>
                        <hr>
                        <p class="text-muted m-t-15">Points: {{ employee.total_points }} <i style="color: #ffcc00;" class="bi bi-star-fill"></i></p>
                   
                        <div class="bg-c-green counter-block m-t-10 p-30 rounded">
                            <a class="btn text-light" href="/account/profile/{{employee.employee.id}}">Read More</a>
                        </div>
                       
                    </div>
                </div>
            </div>
            {% endif %}
            {% if forloop.counter == 3 %}
            <div class="col-md-4">
                <div class="card user-card">
                    <div class="card-header">
                        <h6 class="mb-0 display-6 "><span class="badge bg-c-yellow rounded-5 ">{{ forloop.counter }}rd </span></h6>
                    </div>
                    <div class="card-block">
                        <div class="user-image">
                            <img src="{{ employee.employee.profile_picture.url }}" class="img-radius" alt="User-Profile-Image">
                        </div>
                        <h6 class="f-w-600 m-t-25 m-b-10">{% if employee.employee.first_name %}{{ employee.employee.first_name }} {{ employee.employee.last_name }}{% else %} {{ employee.employee.username }} {% endif %}</h6>
                        <hr>
                        <p class="text-muted m-t-15">Points: {{ employee.total_points }} <i style="color: #ffcc00;" class="bi bi-star-fill"></i></p>
                        <div class="bg-c-yellow counter-block m-t-10 p-30 rounded">
                          <a class="btn text-light" href="/account/profile/{{employee.employee.id}}">Read More</a>
                        </div>
                       
                      
                    </div>
                    
                </div>
                
                
            </div>
            {% endif %}

            {% endfor %}
        </div>
        <div class="row">
            <div class="col-md-12 col-xl-12">
            
  
                <div class="card ">
                  <div class="card-body p-4 ">
        
                    <div class="text-center pt-3 pb-2 d-flex justify-content-center ">
                      
                    </div>
        
                    <table class="table text-white mb-0">
                      <thead>
                        <tr>
                          <th scope="col" width="10%">Rank</th>
                          <th scope="col" width="20%">Employee</th>
                          <th scope="col"class="text-center" width="50%">Points</th>
                          <th scope="col">Tasks</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for employee in ordered_list %}
                        {% if forloop.counter > 3 and forloop.counter <= 10 %}
                        <tr class="fw-normal ">
                          <th class="text-secondary">{{ forloop.counter }}th</th>
                          <th>
                            <img src="{{ employee.employee.profile_picture.url }}"
                              alt="avatar 1" style="width: 45px; height: auto;">
                            <span class="ms-2">{% if employee.employee.first_name %}{{ employee.employee.first_name }} {{ employee.employee.last_name }}{% else %} {{ employee.employee.username }} {% endif %}</span>
                          </th>
                          <td class="text-center">
                            <h6 class="mb-0"><span class="badge bg-c-yellow p-3 rounded-5">Points : {{ employee.total_points }}</span></h6>
                          </td>
                          <td class="align-middle">
                            <h6 class="mb-0"><span class="">{{ employee.number_of_tasks }} Task</span></h6>
                          </td>
                         
                        </tr>
                      {% endif %}
                          
                       {% endfor %}
                      </tbody>
                    </table>
        
        
                  </div>
                </div>
        
              </div>
        </div>
    </div>
    
</div>
{%endblock%}