BavoZone-V.1.0-main/BravoZone/BravoZone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('main.urls')),
    path('account/' , include('account.urls')),
    path('evaluation/' , include('evaluation.urls')),
    
] +static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

BavoZone-V.1.0-main/BravoZone/account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("admin/view/", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/<int:user_id>", views.profile, name="user_profile"),
    path("all/employee/", views.all_emploee, name="all_emploee"),
    path("signup/employee", views.register_employee, name="register_employee"),
    path("profile/<int:user_id>/edit", views.edit_profile, name="edit_profile")
]

BavoZone-V.1.0-main/BravoZone/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('leaderboard/', views.leader_bord, name='leader_bord'),

]

BavoZone-V.1.0-main/BravoZone/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Skill(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class User(AbstractUser):
    email = models.EmailField()
    profile_picture = models.ImageField(upload_to="profile_pictures")
    bio = models.TextField()

    def __str__(self):
        return self.username


class EducationalQualification(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True, related_name="education"
    )
    skills = models.ManyToManyField(Skill, blank=True)
    # skills_list = models.(models.CharField(max_length=255))
    university_name = models.CharField(max_length=100)
    major = models.CharField(max_length=100)
    degree = models.CharField(max_length=50)
    academic_rank = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

BavoZone-V.1.0-main/BravoZone/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Skill, User, EducationalQualification

class SignUpEmployeeForm(UserCreationForm):
    ROLE_CHOICES=(
   
        ('user','User'),
    )
    role = forms.ChoiceField(choices=ROLE_CHOICES)
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name','username', 'password1', 'password2', 'email','role', 'profile_picture']

class SignUpForm(UserCreationForm):
    ROLE_CHOICES=(
        ('admin', 'Admin'),
        ('superadmin','Super Admin'),
        ('user','User'),
    )
    role = forms.ChoiceField(choices=ROLE_CHOICES)
    
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'password1', 'password2', 'email','role', 'profile_picture']

class EducationalQualificationForm(forms.ModelForm):
    class Meta:
        model = EducationalQualification
        fields = ['university_name', 'major', 'degree', 'skills', 'academic_rank']
        widgets = {
            'skills': forms.CheckboxSelectMultiple
        }


class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['name']
        

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

BavoZone-V.1.0-main/BravoZone/account/views.py
from django.shortcuts import render, redirect

from evaluation.models import Task
from .forms import SignUpEmployeeForm, SignUpForm, EducationalQualificationForm
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from .models import User, EducationalQualification
from django.contrib.auth import logout

from evaluation.models import Task


def home(request):
    # users = User.objects.all()
    users = User.objects.filter(is_superuser=False, is_staff=False)
    return render(request, "accounts/admin_view.html", {"users": users})


def signup(request):
    if request.method == "POST":
        user_form = SignUpForm(request.POST, request.FILES)
        print(user_form)
        if user_form.is_valid():
            user = user_form.save()

            role = user_form.cleaned_data["role"]
            if role == "admin":
                user.is_staff = True
            elif role == "superadmin":
                user.is_staff = True
                user.is_superuser = True
            user.save()
            return redirect("account:login")
    else:
        user_form = SignUpForm()
    return render(
        request,
        "accounts/signup.html",
        {"user_form": user_form},
    )


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data["username"]
                password = form.cleaned_data["password"]
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    if user.is_superuser:
                        return redirect("account:home")
                    else:
                        return redirect('main:home_view')
                else:
                    form.add_error(None, "Invalid username or password.")
        else:
            form = LoginForm()
        return render(request, "accounts/login.html", {"form": form})
    return redirect("account:profile")


def logout_view(request):
    logout(request)
    return redirect("account:login")


def profile(request, user_id=None):
    if user_id != None:
        profile_user = User.objects.get(pk=user_id)
        print(profile_user)
    else:
        profile_user = User.objects.get(pk=request.user.id)
      
        print(profile_user)

    task_list = Task.objects.filter(assigned_to=profile_user, status='completed')
    print(task_list)
    return render(request, "accounts/profile.html", {"profile_user": profile_user, 'task_list': task_list})


def all_emploee(request):
    employees = User.objects.filter(is_superuser=False, is_staff=False)
    
    leaderboard_list = []
    for employee in employees:
        employee_tasks = Task.objects.filter(assigned_to=employee)
        print(employee_tasks)
        completed_tasks_points = []
        for task in employee_tasks:
            if task.status == 'completed':
                completed_tasks_points.append(int(task.points))
            
        print(completed_tasks_points)

        leaderboard_list.append({'employee': employee, 'number_of_tasks': len(employee_tasks),'total_points':sum(completed_tasks_points)})
        print(leaderboard_list)


    return render(request, "accounts/all_employee.html", {"users": leaderboard_list})


def register_employee(request):
    user = request.user
    if user.is_authenticated:
        if user.is_superuser:
            if request.method == "POST":
                employee_form = SignUpEmployeeForm(request.POST, request.FILES)
                print(employee_form)
                if employee_form.is_valid():
                    employee = employee_form.save()


                    employee.save()
                    return redirect(f"/account/profile/{employee.id}")
            else:
                employee_form = SignUpEmployeeForm(request.POST, request.FILES)
            return render(
                request,
                "accounts/register_employee.html",
                {"employee_form": employee_form},
            )
        else:
            return render(request, "<h1>You are not Allowed.</h1>")
    else:
        return render(request, "account:login")

    
    # return render(request, "accounts/regester.html", {"users": user})        


def edit_profile(request, user_id):
    if request.user.is_authenticated:
        
        user = User.objects.get(pk=user_id)
        if request.user.is_superuser or request.user == user:
            education_user = EducationalQualification.objects.get_or_create(user=user)
            education_form = EducationalQualificationForm(request.POST)
            print(education_user[0].skills)
            if request.method == "POST":
                # if education_form.is_valid():
                user.first_name = request.POST.get("first_name")
                user.last_name = request.POST.get("last_name")
                user.bio = request.POST.get("bio")
                user.email = request.POST.get("email")

                skills = request.POST.getlist("skills")
                print(skills)

                education_user[0].skills.set(skills)
                education_user[0].major = request.POST.get("major")
                education_user[0].degree = request.POST.get("degree")

                education_user[0].university_name = request.POST.get("university_name")
                education_user[0].save()
                print(education_user)
                user.save()
                # education = education_form.save(commit=False)
                # education.user = user

                # education.save()

                return redirect(f"/account/profile/{user.id}")
            return render(
                request,
                "accounts/edit_profile.html",
                {
                    "profile_id": user_id,
                    "profile_user": user,
                    "education_form": education_form,
                },
            )
        else:
            return render(request, '<h3>your are not allowed</h3>')
    else:
        return render("account:login")

BavoZone-V.1.0-main/BravoZone/account/templates/accounts/admin_view.html
{% extends 'main/base.html' %}
{% block title %} Admin View {% endblock %}
{% block content %}
  {% if user.is_superuser %}
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="clearfix ">
    <div class="container m-5" data-aos="fade-up ">

      <div class="hero-img" data-aos="zoom-out" data-aos-delay="200">
        <img src="/static/img/hero-img.svg" alt="" class="img-fluid">
      </div>

      <div class="hero-info" data-aos="zoom-in" data-aos-delay="100">
        <h2>Manager Page <br></h2>
        <h2 class="mt-5 mb-5 ms-5 text-decoration-none display-6 text-warning  "> {{ user.username }} </h2>
        <div>
            <a href="{%url 'account:register_employee'%}" class="btn-get-started scrollto">Add Employee</a>
            <a href="{%url 'account:logout'%}" class="btn-services scrollto">Logout</a>
          </div>
      </div>

    </div>
  </section><!-- End Hero Section -->
    <!-- ======= Services Section ======= -->
    <section id="services" class="section-">
        <div class="container" data-aos="fade-up">
  
          <header class="section-header  m-5">
            <h3>Employees</h3>
          </header>
  
          <div class="row justify-content-center">
  
            {% for employee in users %}
            {% with employee.education.all|first as education  %}
            <div class="col-md-6 col-lg-5" data-aos="zoom-in" data-aos-delay="200">
              <div class="box">
                <div class="icon"><i class="bi bi-card-checklist" style="color: #e9bf06;"></i></div>
                <h4 class="title"><a href="">{{ employee.username }}</a></h4>
                <p class="description">Employee Number: {{ employee.employee_number }}</p>
                <p class="description">Email: {{ employee.email }}</p>
                <a class="btn" style="color: #e9bf06;" href="/evaluation/tasks/create?assigned_to={{employee.id}}">Assign Task</a>
                <a class="btn" style="color: #e9bf06;" href="{% url 'account:user_profile' user_id=employee.id  %}">View Profile</a>
    
              </div>

            </div>
            {% endwith %}
            {% endfor %}
            {% endif %}

          </div>
  
        </div>
      </section><!-- End Services Section -->
{%endblock%}

BavoZone-V.1.0-main/BravoZone/account/templates/accounts/all_employee.html
{% extends 'main/base.html' %}
{% block title %} Home  {% endblock %}
{% block content %}

<div class="container employee">

    <div class="container">
        <div class="row">
            {% for employee in users %}

            {% with employee.employee.education.all|first as education  %}

            <div class="col-md-4">
                <div class="card user-card">
                   
                    <div class="card-block">
                        <div class="user-image">
                            <img src="{{ employee.employee.profile_picture.url }}" class="img-radius" alt="User-Profile-Image">
                        </div>
                        <h6 class="f-w-600 m-t-25 m-b-10">{% if employee.employee.first_name %} {{ employee.employee.first_name }} {{ employee.employee.last_name }} {% else %} {{ employee.employee.username }} {% endif %}</h6>
                        <p class="text-muted">Email: {{ employee.employee.email }}</p>
                        <hr>
                        <p class="text-secsuss m-t-15">Points: {{ employee.total_points }} <i style="color: #ffcc00;" class="bi bi-star-fill"></i></p>
                    
                        
                        <div class="bg-c-blue counter-block m-t-10 p-30 rounded">
                           <a class="btn text-light" href="/account/profile/{{employee.employee.id}}">Read More</a>
                        </div>
                       
                    </div>
                </div>
            </div>

            
            {% endwith %}
            {% endfor %}
        </div>
    </div>
    
</div>
{%endblock%}

BavoZone-V.1.0-main/BravoZone/account/templates/accounts/edit_profile.html
{% extends 'main/base.html' %}
{% block title %} Edit profile  {% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data" action="{% url 'account:edit_profile' user_id=profile_id %}">
    {% csrf_token %}
    
    <section id="" class="profile">
        <div class="container m-5">
            <div class="container bootstrap snippets bootdey">
                <div class="row">
                  <div class="profile-nav col-md-3">
                      <div class="panel">
                          <div class="user-heading round">
                           {% with profile_user.education.all|first as education %}
                              <a href="#">
                                 <img src="{{ profile_user.profile_picture.url }}" style="width: 130px;" alt="Profile Picture">
                                                                </a>
                                                                <h1 class="mt-4 text-light">{% if profile_user.first_name %}{{ profile_user.first_name }} {{ profile_user.last_name }}{% else %} {{ profile_user.username }} {% endif %}</h1>
                                                                <p class="mt-4">{{ profile_user.email }}</p>
                          </div>
                                    
                          <ul class="nav nav-pills nav-stacked d-flex  ">
                            <li class=" me-5 el col-12 "><a href="{% url 'account:user_profile' user_id=profile_user.id %}"> <i class="fa fa-user ps-2  "></i> Profile </a></li>
                            {% if user.is_superuser or user.id == profile_user.id %}
                            <li class="active el col-12"><a href="{% url 'account:edit_profile' user_id=profile_user.id %}"> <i class="fa fa-edit ps-2 "></i> Edit profile</a></li>
                            {%endif%}
                        </ul>
                      </div>
                    </div>
                        <div class="profile-info col-md-9">
                            
                            <div class="panel">
                                <div class="bio-graph-heading">
                                <textarea name="bio" style="width: 100%;">{{ profile_user.bio }}</textarea>
                                </div>
                        <div class="panel-body bio-graph-info p-5">
                        <h1>University:<input type="text" class="form-control" name="university_name" value="{{ education.university_name }}"/></h1>
                        <div class="row">
                        <div class="bio-row">
                            <p><span>First Name </span>:<input type="text" class="form-control" name="first_name" value="{{ profile_user.first_name }}"/></p>
                        </div>
                        <div class="bio-row">
                            <p><span>Last Name: </span> <input type="text" class="form-control" name="last_name" value="{{ profile_user.last_name }}"/></p>
                            
                            </div>
                        <div class="bio-row">
                        <p><span>Email: </span> <input type="text" class="form-control" name="email" value="{{ profile_user.email }}"/></p>
                        </div>
                        <div class="bio-row">
                        <p><span>Skills </span>
                                {{ education_form.skills }}
                                </p>
                        </div>
                        <div class="bio-row">
                            <p>Academic Degree : <input type="text" class="form-control" name="degree" value="{{ education.degree }}"/> </p>
                            </div>
                        <div class="bio-row">
                        <p><span>Major </span>: <input type="text" class="form-control" name="major" value="{{ education.major }}"/> </p>
                        </div>
                        
                            
                               
                        <button type="submit" >Update</button>
                        </div>
                        </div>
                        </div>
                        <div>
                        {% endwith %}
                      
                        </div>
                        </div>
                        </div>
                        </div>

                        </div>
                        
                        </section>
                    </form>
                        
                        {%endblock%}

                        

BavoZone-V.1.0-main/BravoZone/account/templates/accounts/login.html
{% extends 'main/base.html' %}
{% block title %} Home  {% endblock %}
{% block content %}
<div class="container login">
      <section class="vh-100">
        <div class="container-fluid h-custom">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
              <h1 class="text-center txt fw-bold">Login </h1>
              <form method="post" action="{% url 'account:login' %}">
                {% csrf_token %}
              <!-- Email input -->
                <div class="form-outline mb-4 ">
                  <label class="form-label txt fw-bold" for="form3Example3">UserName </label><br>
                  {{ form.username }}
                </div>
      
                <!-- Password input -->
                <div class="form-outline mb-3">
                  <label class="form-label txt fw-bold" for="id_password">Password:</label><br>
                  {{ form.password }}
                </div>
                <div class="text-center text-lg-start mt-4 pt-2">
                  <button type="submit" class="btn btn-primary btn-lg"
                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
  </div>

 {%endblock%}

{% comment %} <form method="post" action="{% url 'account:login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form> {% endcomment %}

BavoZone-V.1.0-main/BravoZone/account/templates/accounts/profile.html
{% extends 'main/base.html' %}
{% block title %} profile  {% endblock %}
{% block content %}
    <section id="" class="profile">
        <div class="container m-5">
            <div class="container bootstrap snippets bootdey">
                <div class="row">
                  <div class="profile-nav col-md-3">
                      <div class="panel">
                          <div class="user-heading round">
                           {% with profile_user.education.all|first as education %}
                              <a href="#">
                                
                                 <img src="{% if profile_user.profile_picture %}{{ profile_user.profile_picture.url }} {%else%} # {%endif%}" style="width: 130px;" alt="Profile Picture">
                                                                </a>                             
                                    <h1 class="mt-4 text-light">{% if profile_user.first_name %}{{ profile_user.first_name }} {{ profile_user.last_name }}{% else %} {{ profile_user.username }} {% endif %}</h1>
                                    <p>{{ profile_user.email }}</p>
                          </div>
                                    <ul class="nav nav-pills nav-stacked d-flex  ">
                                        <li class="active me-5 el col-12 "><a href="#"> <i class="fa fa-user ps-2  "></i> Profile </a></li>
                                        {% if user.is_superuser or user.id == profile_user.id %}
                                        <li class=" el col-12"><a href="{% url 'account:edit_profile' user_id=profile_user.id %}"> <i class="fa fa-edit ps-2 "></i> Edit profile</a></li>
                                    {%endif%}
                                    </ul>
                      </div>
                    </div>
                        <div class="profile-info col-md-9">
                            
                            <div class="panel">
                                <div class="bio-graph-heading">
                                   {{ profile_user.bio }}
                                </div>
                        <div class="panel-body bio-graph-info p-5">
                        <h1>University:{{ education.university_name }}</h1>
                        <div class="row">
                        <div class="bio-row">
                            <p>ID : {{ profile_user.username }}</p>
                        </div>
                        <div class="bio-row">
                        <p><span>Email</span>:{{ profile_user.email }}</p>
                        </div>
                        <div class="bio-row">
                        <p><span> Skills:</span>

                            <ul>
                                {% for skill in education.skills.all %}
                                <li>{{ skill.name }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="bio-row">
                            <p>Academic Degree : {{ education.degree }}</p>
                            </div>
                        <div class="bio-row">
                        <p> Major  : {{ education.major }}</p>
                        </div>
                       
                        
                        </div>
                        </div>
                        </div>
                        <div>
                        {% endwith %}
                        <div class="row ">
                            {% for task in task_list %}
                            <div class="col-md-6 panel-body p-3 m-3 ">
                                <div class="panel">
                                    <div class="">
                                        <div class="bio-chart">
                                            <div style="display:inline;width:100px;height:100px;"><canvas width="100" height="100px"></canvas><input class="knob" data-width="100" data-height="100" data-displayprevious="true" data-thickness=".2" value="{{ forloop.counter }}" data-fgcolor="#e06b7d" data-bgcolor="#e8e8e8" style="width: 54px; height: 33px; position: absolute; vertical-align: middle; margin-top: 33px; margin-left: -77px; border: 0px; font-weight: bold; font-style: normal; font-variant: normal; font-stretch: normal; font-size: 20px; line-height: normal; font-family: Arial; text-align: center; color: rgb(224, 107, 125); padding: 0px; -webkit-appearance: none; background: none;"></div>
                                        </div>
                                        <div class="bio-desk">
                                            <h4 class="red">{{ task.name }}</h4>
                                            <p>Started : {{ task.start_time }}</p>
                                            <p>Deadline : {{ task.end_time }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        </div>
                        </div>
                        </div>

                        </div>
                        </section>
                        {%endblock%}

                        

BavoZone-V.1.0-main/BravoZone/account/templates/accounts/register_employee.html
{% extends 'main/base.html' %}
{% block title %} Sign Up  {% endblock %}
{% block content %}
<div class="container login">
  <section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
            <h1 class="text-center txt fw-bold">Register Employee</h1>
   
            <form method="POST" enctype="multipart/form-data" action="{% url 'account:register_employee' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 mb-4">
              <label class="form-label txt fw-bold fontsize" for="id_username">First Name:</label>
              {{ employee_form.first_name }} </br>
              <label class="form-label text-danger fo" for="form3Example3">*Enter the first letter as a capital </label>
              
            <label class="form-label txt fw-bold fontsize" for="id_username">Employee Number:</label>
          {{ employee_form.username }} </br>
          <label class="form-label text-danger fo" for="form3Example3">*Enter a unique number </label>
            <label for="id_password1" class="form-label txt fw-bold fontsize">Password:</label>
            {{ employee_form.password1 }}</br>
            <label class="form-label text-danger fo" for="form3Example3">*Enter a Strong Password </label>
          
            <label for="id_profile_picture"class="form-label txt fw-bold fontsize">Profile Picture:</label>
            {{ employee_form.profile_picture }}
        </div>
        <div class="col-md-6 mb-4">
          <label for="id_email"class="form-label txt fw-bold fontsize">Last Name:</label>
            {{ employee_form.last_name }} </br></br>
            <label for="id_email"class="form-label txt fw-bold fontsize">Email:</label>
            {{ employee_form.email }} </br></br>
            <label for="id_password2"class="form-label txt fw-bold fontsize">Confirm Password:</label>
            {{ employee_form.password2 }}
         
            <input type="text" name="role" value="user" hidden>
            <!-- <label for="id_skills"class="form-label txt fw-bold fontsize">Skills:</label>
            {{ qualification_form.skills }}
             -->
        </div>
        <div class="text-center  mt-4 pt-2">
            <button type="submit" class="btn btn-primary btn-lg "
              style="padding-left: 2.5rem; padding-right: 2.5rem;">Register</button>
          </div>
        <!-- <input type="submit" value="Sign Up"> -->
    </form>
</div>
</div>
</div>
  </section>
  </div>
{%endblock%}

BavoZone-V.1.0-main/BravoZone/account/templates/accounts/signup.html
{% extends 'main/base.html' %}
{% block title %} Sign Up  {% endblock %}
{% block content %}
<div class="container login">
  <section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <h1 class="text-center txt fw-bold">Manager Sign Up</h1>
    <form method="POST" enctype="multipart/form-data" action="{% url 'account:signup' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 mb-4">
            <label class="form-label txt fw-bold fontsize" for="id_username">Username:</label>
          {{ user_form.username }} 
            <label for="id_password1" class="form-label txt fw-bold fontsize">Password:</label>
            {{ user_form.password1 }}
    
            <input type="text"  name="role" id="id_role" value="superadmin" hidden>

            <label for="id_profile_picture"class="form-label txt fw-bold fontsize">Profile Picture:</label>
            {{ user_form.profile_picture }}
        </div>
        <div class="col-md-6 mb-4">
            <label for="id_email"class="form-label txt fw-bold fontsize">Email:</label>
            {{ user_form.email }} 
            <label for="id_password2"class="form-label txt fw-bold fontsize">Confirm Password:</label>
            {{ user_form.password2 }}
          
           
        </div>
        <div class="text-center  mt-4 pt-2">
            <button type="submit" class="btn btn-primary btn-lg "
              style="padding-left: 2.5rem; padding-right: 2.5rem; ">Sign Up</button>
          </div>
        <!-- <input type="submit" value="Sign Up"> -->
    </form>
</div>
</div>
</div>
  </section>
  </div>
{%endblock%}