BavoZone-V.1.0-main/BravoZone/BravoZone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('main.urls')),
    path('account/' , include('account.urls')),
    path('evaluation/' , include('evaluation.urls')),
    
] +static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

BavoZone-V.1.0-main/BravoZone/evaluation/urls.py
from django.urls import path
from evaluation import views


app_name = "evaluation"

urlpatterns = [
    path("tasks/", views.task_list, name="task_list"),
    path("tasks/create/", views.task_create, name="task_create"),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),
    path('task/<int:task_id>/update_status/', views.update_task_status, name='update_task_status'),
    path('task/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('mytask', views.my_tasks, name='my_task_list')
]

BavoZone-V.1.0-main/BravoZone/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('leaderboard/', views.leader_bord, name='leader_bord'),

]

BavoZone-V.1.0-main/BravoZone/evaluation/models.py
from django.utils import timezone
from django.db import models
from account.models import User

class Task(models.Model):
    TASK_STATUS_CHOICES = (
        ('completed', 'Completed'),
        ('in_process', 'In Process'),
        ('deletion', 'Deletion of the Task'),
    )

    name = models.CharField(max_length=255)
    content = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    points = models.IntegerField(choices=zip(range(1, 11), range(1, 11)))
    status = models.CharField(max_length=20, choices=TASK_STATUS_CHOICES)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks', 
                                    limit_choices_to={"is_superuser": False})


    def __str__(self):
        return self.name
    
    def update_status(self):
        if self.status != 'completed' and timezone.now() > self.end_time:
            self.status = 'completed'
            self.save()

BavoZone-V.1.0-main/BravoZone/evaluation/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'content', 'start_time', 'end_time', 'points', 'status', 'assigned_to']
        widgets = {
            'start_time': forms.DateTimeInput(format=('%Y-%m-%dT%H:%M'), attrs={'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(format=('%Y-%m-%dT%H:%M'), attrs={'type': 'datetime-local'})
        }

BavoZone-V.1.0-main/BravoZone/evaluation/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from account.models import User
from .models import Task
from .forms import TaskForm

@login_required
def task_create(request):
    
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('evaluation:task_list')
    else:
        employees = User.objects.filter(is_superuser=False, is_staff=False)

        if request.method == 'GET' and 'assigned_to' in request.GET:
            assigned_to = request.GET['assigned_to']
            if assigned_to is not None and assigned_to != '':
                form = TaskForm(initial={'assigned_to': request.GET['assigned_to']})
            else:
                form = TaskForm()
        else:
            form = TaskForm()
    return render(request, 'evaluation/task_create.html', {'form': form, 'employees': employees})


def task_list(request):
    all_tasks = None
    if request.user.is_superuser:
        all_tasks = Task.objects.all()
    # else:
    #     all_tasks = Task.objects.filter(assigned_to=request.user.id)
    return render(request, 'evaluation/task_list.html', {'all_tasks': all_tasks})


def my_tasks(request):
    all_tasks = Task.objects.filter(assigned_to=request.user.id)
    return render(request, 'evaluation/mytask.html', {'all_tasks': all_tasks})

def task_detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.update_status() 
    print(f"user: {request.user}, task_assigned_to: {task.assigned_to}")
    return render(request, 'evaluation/task_detail.html', {'task': task})


def update_task_status(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    
    if request.method == 'POST':
        new_status = request.POST.get('status')
        task.status = new_status
        task.save()
            
        return redirect('evaluation:task_detail', task_id=task_id)

def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    task.delete()
    return redirect('evaluation:task_list')

BavoZone-V.1.0-main/BravoZone/evaluation/templates/evaluation/mytask.html
{% extends 'main/base.html' %}
{% block title %} Home  {% endblock %}
{% block content %}
<link rel="stylesheet" href="https://allyoucan.cloud/cdn/icofont/1.0.1/icofont.css" integrity="sha384-jbCTJB16Q17718YM9U22iJkhuGbS0Gd2LjaWb4YJEZToOPmnKDjySVa323U+W7Fv" crossorigin="anonymous">

<div class="container p-3">
    <div class="row mt-5 pt-5">
        <div class="col-md-">
            <div class="osahan-account-page-right shadow-lg bg-white p-4 h-100">
                <div class="tab-content p-3 m-5" id="myTabContent">
                    <div class="tab-pane fade  active show" id="addresses" role="tabpanel" aria-labelledby="addresses-tab">
                        <h2 class=" mt-0 mb-4 fw-bold text-center"style="color: #003b7a;">My Task</h2>
                        <div class="row">  
                          {% for task in all_tasks %}
                            <div class="col-md-6">
                                <div class="bg-white card addresses-item mb-4 shadow-lg">
                                    <div class="gold-members p-4">
                                        <div class="media">
                                            <div class="mr-3"><i class="icofont-briefcase icofont-3x"></i></div>
                                            <div class="media-body">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                            <h6 class="mb-1 fw-bold">{{ task.name }}</h6>
                                                        </div>
                                                    <div class="col-md-6">
                                                            <h6><span class="pointptn">{{ task.points }} Points</span></h6>
                                                    </div>
                                                </div>
                                                <p>End Date: {{ task.end_time|date:"d/m/Y" }}</p>
                                                <h6>{% if task.status == 'completed' %}
                                                    Completed
                                                    {% endif %}
                              
                                                    {% if task.status == 'in_process' %}
                                                    In Process
                                                    {% endif %}
                              
                                                    {% if task.status == 'deletion' %}
                                                    Deletion
                                                    {% endif %}</h6> <hr/>
                                                <a href="{% url 'evaluation:task_detail' task.id %}"><button class="cta">
                                                    <span>View Details</span>
                                                    <svg viewBox="0 0 13 10" height="10px" width="15px">
                                                      <path d="M1,5 L11,5"></path>
                                                      <polyline points="8 1 12 5 8 9"></polyline>
                                                    </svg>
                                                  </button></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

BavoZone-V.1.0-main/BravoZone/evaluation/templates/evaluation/task_create.html
{% extends 'main/base.html' %}
{% block title %} Add Task  {% endblock %}
{% block content %}
<div class="herotask">
    <div class="row text-center patask">
      <h1 class="txt fw-bold text-white">Add Task</h1>
    </div>
    <div class="container pb-5 ">
        <form method="post" action="{% url 'evaluation:task_create' %}">
            {% csrf_token %}
            <div class="row borderr ">
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <label class="form-label txt fw-bold mt-3" for="id_name" >Task Title  </label><br>
                    {{ form.name }}<br>
                    <label class="form-label txt fw-bold mt-3" for="id_assigned_to" >Task Member  </label><br>
                    <select name="assigned_to" required id="id_assigned_to">
                        <option value="" selected>---------</option>
                        {% for employee in employees %}
                        <option value="{{ employee.id }}">{% if employee.first_name %} {{ employee.first_name }} {{employee.last_name}} {% else %} {{ employee.username }} {% endif %} </option>
                      {% endfor %}
                      </select>
                    <div class="row">
                        <div class="col-md-6 mb-4">
                            <label class="form-label txt fw-bold fontsize mt-3 date" for="id_start_time">Start Date</label>
                            {{ form.start_time }}
                        </div>
                        <div class="col-md-6 mb-4 ps-5">
                            <label class="form-label txt fw-bold fontsize mt-3 date" for="id_end_time">End Date</label>
                            {{ form.end_time }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-4">
                            <label class="form-label txt fw-bold fontsize mt-3 date" for="id_status">Status </label><br>
                            {{ form.status }} <br>
                        </div>
                        <div class="col-md-6 mb-4">
                            <label class="form-label txt fw-bold fontsize mt-3 date" for="id_points">Select Points</label><br>
                            {{ form.points }}
                        </div>
                    </div>
                </div>
                <div class="col-md-9 col-lg-6 col-xl-5 offset-xl-1">
                    <label class="form-label txt fw-bold mt-3" for="id_content">Task Description   </label><br>
                    {{ form.content }}
                </div>
                <div class="row justify-content-center align-items-center mt-3">
                    <button class="button " type="submit">
                      <p>Create</p>
                    </button>
                  </div>
                </div>
        </form>
    </div>
</div>

{%endblock%}
<!-- <!DOCTYPE html>
<html>
<head>
    <title>Create Task</title>
</head>
<body>
    <h1>Create Task</h1>
    <form method="post" action="{% url 'evaluation:task_create' %}">
        {% csrf_token %}
        <label for="id_name">Name:</label>
        {{ form.name }}
        <br>
        <label for="id_content">Content:</label>
        {{ form.content }}
        <br>
        <label for="id_start_time">Start Time:</label>
        {{ form.start_time }}
        <br>
        <label for="id_end_time">End Time:</label>
        {{ form.end_time }}
        <br>
        <label for="id_points">Points:</label>
        {{ form.points }}
        <br>
        <label for="id_status">Status:</label>
        {{ form.status }}
        <br>
        <label for="id_assigned_to">Assigned To:</label>
        
        <select name="assigned_to" required id="id_assigned_to">
            <option value="" selected>---------</option>
            {% for employee in employees %}
            <option value="{{ employee.id }}">{% if employee.first_name %} {{ employee.first_name }} {{employee.last_name}} {% else %} {{ employee.username }} {% endif %} </option>
          {% endfor %}
          </select>
        <br>
        <button type="submit">Create</button>
    </form>
</body>
</html> -->

BavoZone-V.1.0-main/BravoZone/evaluation/templates/evaluation/task_detail.html
{% extends 'main/base.html' %}
{% block title %} Home  {% endblock %}
{% block content %}
<link rel="stylesheet" href="https://allyoucan.cloud/cdn/icofont/1.0.1/icofont.css" integrity="sha384-jbCTJB16Q17718YM9U22iJkhuGbS0Gd2LjaWb4YJEZToOPmnKDjySVa323U+W7Fv" crossorigin="anonymous">

<div class="container pt-5 pb-4">
    <div class="row">
        <div class="col-md pt-5">
            <div class="osahan-account-page-right shadow-lg bg-white p-4 h-100">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade  active show" id="addresses" role="tabpanel" aria-labelledby="addresses-tab">
                        <div class="row">  
                            <div class="col-md">
                                <div class="bg-white card addresses-item mb-4 shadow-lg">
                                    <div class="gold-members p-4">
                                        <div class="media">
                                            <div class="mr-3"><i class="icofont-briefcase icofont-3x"></i></div>
                                            <div class="media-body">
                                                <div class="row text-center">
                                                    <div class="col-md-">
                                                            <h2 class="mb-1 fw-bold">{{ task.name }} </h2><br>
                                                            <h6 class="mb-1 ">{{ task.content }} </h6><br>
                                                        <div class="row ">
                                                            <div class="col-md-6 mb-4">
                                                                <h6><i class="bi bi-calendar-week"></i>   {{ task.start_time }}</h6>
                                                            </div>
                                                            <div class="col-md-6 mb-4 ps-5">
                                                                <h6><i class="bi bi-calendar-week"></i>   {{ task.end_time }}</h6>
                                                            </div>
                                                        </div>
                                                        <h6><span class="pointptn">Points : {{ task.points }}🌟</span></h6>
                                                        {{ task.status }}
                                                        {% if user == task.assigned_to %}
                                                        {% if task.status != 'completed' %}
                                                            <form method="POST" action="{% url 'evaluation:update_task_status' task.id %}">
                                                                {% csrf_token %}
                                                                <select name="status">
                                                                    <option value="completed">Completed</option>
                                                                    <option value="in_progress">In Progress</option>
                                                                    <option value="not_started">Not Started</option>
                                                                </select>
                                                                <button type="submit">Save</button>
                                                            </form>
                                                        {% endif %}
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}
<!-- <!DOCTYPE html>
<html>
<head>
    <title>Task Detail</title>
</head>
<body>
    <h1>Task Detail</h1>
    <p><strong>Name:</strong> {{ task.name }}</p>
    <p><strong>Content:</strong> {{ task.content }}</p>
    <p><strong>Start Time:</strong> {{ task.start_time }}</p>
    <p><strong>End Time:</strong> {{ task.end_time }}</p>
    <p><strong>Points:</strong> {{ task.points }}</p>
    <p><strong>Status:</strong> {{ task.status }}</p>

    {% if task.status != 'completed' %}
        <form method="POST" action="{% url 'evaluation:update_task_status' task.id %}">
            {% csrf_token %}
            <select name="status">
                <option value="completed">Completed</option>
                <option value="in_progress">In Progress</option>
                <option value="not_started">Not Started</option>
            </select>
            <button type="submit">Save.</button>
        </form>
    {% endif %}

    <a href="{% url 'evaluation:task_list' %}">Back</a>
</body>
</html> -->

BavoZone-V.1.0-main/BravoZone/evaluation/templates/evaluation/task_list.html
{% extends 'main/base.html' %}
{% block title %} Home  {% endblock %}
{% block content %}
<div class="container employee ">
<section class="vh-100 gradient-custom-2 mb-3"> 
   
    <div class="container ">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-12 col-xl-10">
            <div class="card-footer text-end p-3">
    {% if user.is_superuser %}
                <a href="{% url 'evaluation:task_create' %}"><button class="btn  text-light mb-4" style="  background:#0b6bd3; ">Add Task</button></a>
              {% endif %}
              </div>
  
          <div class="card ">
            <div class="card-body p-4 text-white">
  
              <div class="text-center pt-3 pb-5">
                <h2 class="my-4"><i class="bi bi-list-stars"></i></span> Task List </h2>
              </div>
  
              <table class="table text-white mb-0">
                <thead>
                  <tr>
                    <th scope="col">Team Member</th>
                    <th scope="col">Task</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
{% for task in all_tasks %}

                  <tr class="fw-normal">
                    <th>
                      {% with task.assigned_to as task_user %}
                      <img src="{{ task_user.profile_picture.url }}"
                        alt="avatar 1" style="width: 45px; height: auto; border-radius: 50%;">

                      <span class="ms-2">{% if task_user.first_name %}{{ task_user.first_name }} {{ task_user.last_name }} {% else %} {{task_user.username}} {% endif %}</span>
                      {% endwith %}
                    </th>
                    <td class="align-middle">
                      <a href="{% url 'evaluation:task_detail' task.id %}"><span>{{ task.name }}</span></a>
                    </td>
                    <td class="align-middle">
                      {% if task.status == 'completed' %}
                      <h6 class="mb-0"><span class="badge bg-danger">Completed</span></h6>
                      {% endif %}

                      {% if task.status == 'in_process' %}
                      <h6 class="mb-0"><span class="badge bg-success">In Process</span></h6>
                      {% endif %}

                      {% if task.status == 'not_started' %}
                      <h6 class="mb-0"><span class="badge bg-warning">Not Started</span></h6>
                      {% endif %}
                    </td>
                    
                    <td class="align-middle">
                     
                      <a href="{% url 'evaluation:delete_task' task.id %}" data-mdb-toggle="tooltip" title="Remove">
                        <i class="bi bi-trash text-black"></i>
                        <!-- <i class="fas fa-trash-alt fa-lg text-warning"></i> -->
                          
                        </a>
                    </td>
                  </tr>
                  {% endfor %}
                  
                 
                    
                 
                </tbody>
              </table>
  
  
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </section>
</div>

{%endblock%}

{% comment %} ---------------------------all_tasks ----------------------- {% endcomment %}

<!DOCTYPE html>
<html>
<head>
    <title>Task List</title>
</head>
<body>
    {% if user.is_superuser %}
    <h1>Task List (Supervisor {{ user.username }})</h1>
    
{% for task in all_tasks %}
    <h2>{{ task.name }}</h2>
    <p>{{ task.content }}</p>
    <p>Start Time: {{ task.start_time }}</p>
    <p>End Time: {{ task.end_time }}</p>
    <p>Points: {{ task.points }}</p>
    <p>Status: {{ task.status }}</p>
    <p>Assigned to: {{ task.assigned_to }}</p>

    <a href="{% url 'evaluation:task_detail' task.id %}">View Details</a>

    <hr>
{% empty %}
    <p>No tasks available.</p>
{% endfor %}
<a href="{% url 'evaluation:task_create' %}">Create New Task</a>
{% else %}
<h1>Task List ({{ user.username }})</h1>
    
{% for task in user.tasks.all %}
    <h2>{{ task.name }}</h2>
    <p>{{ task.content }}</p>
    <p>Start Time: {{ task.start_time }}</p>
    <p>End Time: {{ task.end_time }}</p>
    <p>Points: {{ task.points }}</p>
    <p>Status: {{ task.status }}</p>
    <a href="{% url 'evaluation:task_detail' task.id %}">View Details</a>

    <hr>
{% empty %}
    <p>No tasks available.</p>
{% endfor %}
{% endif %}
</body>